config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  post 'cart/summary', to: 'cart#summary', as: 'cart_summary'
  get 'cart/summary', :to => 'cart#summary'
  post 'cart/update', to: 'cart#update', as: 'cart_update'
  get 'pages/:permalink' => 'pages#permalink' , as: 'permalink' #using it in ruby: permalink_path
  root :to => "pet_groups#index"
  resources :breeds, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :pet_groups, only: [:index, :show]
  resources :cart, only: [:create, :destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Stripe routing
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_one_attached :image
  belongs_to :pet_group
  has_many :pets
  # has_many :orders, through: :breed_orders
  validates :name, uniqueness: true
  validates :name, :price, presence: true
  validates :price, numericality: true

  def to_builder
    Jbuilder.new do |breed|
      breed.name name
      breed.amount (price.round(2) * 100).to_i
      breed.quantity qty
      breed.description name
      breed.currency "cad"
    end
  end
end

app/models/breed_order.rb
class BreedOrder < ApplicationRecord
  belongs_to :order
  belongs_to :breed

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  # has_many :breeds, through: :breed_orders
end

app/models/page.rb
class Page < ApplicationRecord
  has_one_attached :image
  validates :title, :content, :permalink, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :image
  belongs_to :breed
  validates :name, presence: true
end

app/models/pet_group.rb
class PetGroup < ApplicationRecord
  has_one_attached :image
  has_many :breeds
  validates :name, presence: true, uniqueness: true
  validates :total_pets, numericality: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_customer!
  before_action :set_variables, :initialize_session
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :cart

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :province, :province_id, :city, :street, :potal_code])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :province, :province_id, :city, :street, :potal_code])
  end

  def set_variables
    @pet_groups_nav = PetGroup.includes(:breeds).page(params[:page])
  end

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def cart
    # You can pass an array of ids, and you'll get back a collection
    Breed.find(session[:shopping_cart])
    # pass an array of product id's.. get a collection of products!
  end
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = Breed.includes(:pet_group, :pets).page(params[:page])
  end

  def show
    @breed = Breed.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    breed_search = params[:breed]
    breed_search_2 = breed_search[:pet_group_id]
    puts breed_search_2
    if(breed_search_2.empty?)
      @breeds = Breed.where("name LIKE ?", wildcard_search).page(params[:page])
      if @breeds.empty?
        @breeds = Breed.where("description LIKE ?", wildcard_search).page(params[:page])
      end
    else
      @breeds = Breed.where("lower(name) LIKE ? AND pet_group_id = ?", wildcard_search, breed_search_2).page(params[:page])

      if @breeds.empty?
        @breeds = Breed.where("lower(description) LIKE ? AND pet_group_id = ?", wildcard_search, breed_search_2).page(params[:page])
      end
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_customer!
  # POST /cart
  # Data sent as form data (params)
  def create
    # Add params[:id] to cart
    # The logger will show in the rails server.. super useful for debugging!!
    logger.debug("Adding #{params[:id]} to cart.")
    breed_id = params[:id].to_i
    session[:shopping_cart] << breed_id

    breed = Breed.find(breed_id)
    breed.update(qty: params[:qty])
    flash[:notice] = "➕ #{breed.name} added to cart."

    redirect_to pet_groups_path
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id] from cart
    logger.debug("Removing #{params[:id]} from cart.")
    breed_id = params[:id].to_i
    session[:shopping_cart].delete(breed_id)

    breed = Breed.find(breed_id)
    breed.update(qty: 1)
    flash[:notice] = "➖ #{breed.name} Removed from cart."

    redirect_to pet_groups_path
  end

  # Cart summary
  def summary
    prov_id = current_customer.province.id
    @prov = Province.find(prov_id)

    subtotal = 0
    cart.each do |breed|
      subtotal += breed.price * breed.qty
    end
    if @prov.pst.nil?
      pst = 0
    else
      pst = @prov.pst
    end
    if !@prov.hst.nil?
      hst = @prov.hst
    else
      hst = @prov.gst + pst
    end
    total = subtotal * (1 + hst)

    order = current_customer.orders.find_or_create_by(
      total: total,
      gst: @prov.gst,
      pst: pst,
      hst: hst,
      status: "new"
    )
  end

  # Update cart when user input the quantity
  def update
    breed = Breed.find_by_name(params[:name])
    breed.update(qty: params[:qty])
    redirect_to cart_summary_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create

    # Establish a connection with stripe
    @session = Stripe::Checkout::Session.create({
      payment_method_types: ["card"],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
      line_items: cart.collect { |item| item.to_builder.attributes! },
    })
    # Redirect to stripe payment screen
    respond_to do |format|
      format.js #render app/views/checkout/create.js.erb
    end
  end

  def success
    # Transaction success
  end

  def cancel
    # Something went wrong
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def permalink
    @about = Page.find_by(permalink: params[:permalink])
  end
end

app/controllers/pet_groups_controller.rb
class PetGroupsController < ApplicationController
  def index
    @pet_groups = PetGroup.includes(:breeds).page(params[:page])
  end

  def show
    @pet_group = PetGroup.find(params[:id])
    @pg_pag = @pet_group.breeds.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pet_groups_helper.rb
module PetGroupsHelper
end

app/views/breeds/index.html.erb
<h2>List of Breeds available for adoption</h2>


<%= paginate @breeds , window: 1 %>

<div class="row">
  <% @breeds.each do |breed| %>
    <div class="col-md-4">
      <% if breed.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag breed.image.variant(resize_to_limit: [250, 250]).processed, alt:"Picture"  %>
          </figure>
        </div>
      <% else %>
        <img src="<%= breed.image_URL %>" alt="<%= breed.name %> image" />
      <% end %>
      <p><%= link_to breed.name, breed %></p>
      <p><%= link_to breed.pet_group.name, breed.pet_group %></p>
      <p><%= number_to_currency breed.price %></p>

      <% if cart.include?(breed) %>
        <%= button_to cart_path(breed), method: :delete do %>
          Remove From Cart
        <% end %>
      <% else %>
        <%= form_with url: cart_index_path, method: :post do %>
          <%= hidden_field_tag(:id, breed.id) %>
          <%= button_tag 'Add to Cart' %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @breeds , window: 1 %>

app/views/breeds/search.html.erb
<h2>Search for: <span class="light"><%= params[:keywords] %></span></h2>
<h3>Found: <span class="light"><%= pluralize(@breeds.count, 'Breeds') %></span></h3>

<%= paginate @breeds , window: 1 %>

<div class="row">
  <% @breeds.each do |breed| %>
    <div class="col-4">
      <% if breed.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag breed.image.variant(resize_to_limit: [250, 250]).processed, alt:"Picture"  %>
          </figure>
        </div>
      <% else %>
        <img src="<%= breed.image_URL %>" alt="<%= breed.name %> image" />
      <% end %>
      <p><%= link_to breed.name, breed %></p>
      <p><%= link_to breed.pet_group.name, breed.pet_group %></p>
      <p><%= number_to_currency breed.price %></p>

      <% if cart.include?(breed) %>
        <%= button_to cart_path(breed), method: :delete do %>
          Remove From Cart
        <% end %>
      <% else %>
        <%= form_with url: cart_index_path, method: :post do %>
          <%= hidden_field_tag(:id, breed.id) %>
          <%= button_tag 'Add to Cart' %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate @breeds , window: 1 %>

app/views/breeds/show.html.erb
<h2><%= @breed.name%></h2>

<div class="row">
  <div class="col-sm-8">
    <div class="d-inline-block margin-top">
      <h3>Breed: <span class="light"><%= @breed.name%></span></h3>
      <p><span class="bold">Pet Type:</span> <%= link_to @breed.pet_group.name, @breed.pet_group %></p>
      <p><%= @breed.description %></p>
      <p><span class="bold">Available for adoption:</span> <%= @breed.qty %></p>
      <p><span class="bold">Average Price:</span> $<%= number_to_currency @breed.price %></p>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="d-inline float-end margin-top">
      <% if @breed.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag @breed.image.variant(resize_to_limit: [250, 250]).processed, alt:"Picture"  %>
          </figure>
        </div>
      <% else %>
        <img src="<%= @breed.image_URL %>" alt="<%= @breed.name %> image" />
      <% end %>
    </div>
  </div>
</div>

app/views/cart/summary.html.erb
<div class="row">
  <div class="col-sm-8">
    <h2>Adoption Cart</h2>
    <small class="float-right"><%= pluralize(cart.size, 'Items') %></small>
    <% if cart.present? %>
      <% cart.each do |breed| %>
        <div class="row">
          <div class="col-sm-3">
            <%= breed.name %>
          </div>
          <div class="col-sm-5">
            <%= form_with url: cart_update_path, method: :post do %>
              <%= number_field_tag :qty, breed.qty %>
              <%= hidden_field_tag(:name, breed.name) %>
              <%= button_to 'update Cart', cart_update_path %>
            <% end %>
          </div>
          <div class="col-sm-3">
            <% if !breed.qty.nil? %>
              <%= number_to_currency(breed.price * breed.qty) %>
            <% else %>
              <%= breed.qty %>
            <% end %>
          </div>
          <div class="col-sm-1">
            <%= link_to 'X', cart_path(breed), method: :delete %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <h2>Summary</h2>
    <% if cart.present?
      subtotal = 0
    %>
      <% cart.each do |breed|
        subtotal += breed.price * breed.qty
      end %>
      <% if @prov.pst.nil?
        pst = 0
      else
        pst = @prov.pst
      end %>
      <ul>
        <li>GST: <%= @prov.gst %></li>
        <li>PST: <%= pst %></li>
        <% if !@prov.hst.nil? %>
          <li>HST: <%= hst = @prov.hst %></li>
        <% else %>
          <li>HST: <%= hst = @prov.gst + pst %></li>
        <% end %>
        <li>Total Price: <%= number_to_currency(subtotal * (1 + hst)) %></li>
      </ul>
      <%= button_to 'Check Out', checkout_create_path, remote: true %>
    <% end %>
  </div>
</div>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function(result) {
  console.log(result.error.message);
})

app/views/pet_groups/index.html.erb
<h2>List of Animals available for adoption</h2>

<div class="row">
  <% @pet_groups.each do |pg| %>
    <div class="col-4">
      <% if pg.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag pg.image.variant(resize_to_limit: [250, 250]).processed, alt:"Picture" %>
          </figure>
        </div>
      <% else %>
        <%= image_tag pg.image_URL, alt: "Picture" %>
      <% end %>
      <p><%= link_to pg.name, pg %></p>
    </div>
  <% end %>
</div>

app/views/pet_groups/show.html.erb
<h2>Aninmal: <span class="light"><%= @pet_group.name%></span></h2>

<% if @pet_group.breeds.count > 10 %>
  <%= paginate @pg_pag , window: 1 %>
<% end %>
  <div class="row">
    <% @pg_pag.each do |breed| %>
      <div class="col-4">
        <% if breed.image.present? %>
          <div class="card-image">
            <figure class="image">
              <%= image_tag breed.image.variant(resize_to_limit: [250, 250]).processed, alt:"Picture"  %>
            </figure>
          </div>
        <% else %>
          <img src="<%= breed.image_URL %>" alt="<%= breed.name %> image" />
        <% end %>
        <p><%= link_to breed.name, breed %></p>
        <p><%= number_to_currency breed.price %></p>
          <%= form_with url: cart_index_path, method: :post do %>
            <%= hidden_field_tag(:id, breed.id) %>
            <%= number_field_tag :qty, '1' %>
            <%= button_tag 'Add to Cart' %>
          <% end %>
        <%# end %>
      </div>
    <% end %>
  </div>
<% if @pet_group.breeds.count > 10 %>
  <%= paginate @pg_pag , window: 1 %>
<% end %>