config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  post 'cart/summary', to: 'cart#summary', as: 'cart_summary'
  get 'cart/summary', :to => 'cart#summary'
  post 'cart/update', to: 'cart#update', as: 'cart_update'
  get 'pages/:permalink' => 'pages#permalink' , as: 'permalink' #using it in ruby: permalink_path
  root :to => "pet_groups#index"
  resources :breeds, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  resources :pet_groups, only: [:index, :show]
  resources :cart, only: [:create, :destroy]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Stripe routing
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_one_attached :image
  belongs_to :pet_group
  has_many :pets
  # has_many :orders, through: :breed_orders
  validates :name, uniqueness: true
  validates :name, :price, presence: true
  validates :price, numericality: true

  def to_builder
    Jbuilder.new do |breed|
      breed.name name
      breed.amount (price.round(2) * 100).to_i
      breed.quantity qty
      breed.description name
      breed.currency "cad"
    end
  end
end

app/models/breed_order.rb
class BreedOrder < ApplicationRecord
  belongs_to :order
  belongs_to :breed

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :province
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  # has_many :breeds, through: :breed_orders
end

app/models/page.rb
class Page < ApplicationRecord
  has_one_attached :image
  validates :title, :content, :permalink, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_one_attached :image
  belongs_to :breed
  validates :name, presence: true
end

app/models/pet_group.rb
class PetGroup < ApplicationRecord
  has_one_attached :image
  has_many :breeds
  validates :name, presence: true, uniqueness: true
  validates :total_pets, numericality: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = Breed.includes(:pet_group, :pets).page(params[:page])
  end

  def show
    @breed = Breed.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    breed_search = params[:breed]
    breed_search_2 = breed_search[:pet_group_id]
    puts breed_search_2
    if(breed_search_2.empty?)
      @breeds = Breed.where("name LIKE ?", wildcard_search).page(params[:page])
      if @breeds.empty?
        @breeds = Breed.where("description LIKE ?", wildcard_search).page(params[:page])
      end
    else
      @breeds = Breed.where("lower(name) LIKE ? AND pet_group_id = ?", wildcard_search, breed_search_2).page(params[:page])

      if @breeds.empty?
        @breeds = Breed.where("lower(description) LIKE ? AND pet_group_id = ?", wildcard_search, breed_search_2).page(params[:page])
      end
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_customer!
  # POST /cart
  # Data sent as form data (params)
  def create
    # Add params[:id] to cart
    # The logger will show in the rails server.. super useful for debugging!!
    logger.debug("Adding #{params[:id]} to cart.")
    breed_id = params[:id].to_i
    session[:shopping_cart] << breed_id

    breed = Breed.find(breed_id)
    breed.update(qty: params[:qty])
    flash[:notice] = "➕ #{breed.name} added to cart."

    redirect_to pet_groups_path
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id] from cart
    logger.debug("Removing #{params[:id]} from cart.")
    breed_id = params[:id].to_i
    session[:shopping_cart].delete(breed_id)

    breed = Breed.find(breed_id)
    breed.update(qty: 1)
    flash[:notice] = "➖ #{breed.name} Removed from cart."

    redirect_to pet_groups_path
  end

  # Cart summary
  def summary
    prov_id = current_customer.province.id
    @prov = Province.find(prov_id)

    subtotal = 0
    cart.each do |breed|
      subtotal += breed.price * breed.qty
    end
    if @prov.pst.nil?
      pst = 0
    else
      pst = @prov.pst
    end
    if !@prov.hst.nil?
      hst = @prov.hst
    else
      hst = @prov.gst + pst
    end
    total = subtotal * (1 + hst)

    order = current_customer.orders.find_or_create_by(
      total: total,
      gst: @prov.gst,
      pst: pst,
      hst: hst,
      status: "new"
    )
  end

  # Update cart when user input the quantity
  def update
    breed = Breed.find_by_name(params[:name])
    breed.update(qty: params[:qty])
    redirect_to cart_summary_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create

    # Establish a connection with stripe
    @session = Stripe::Checkout::Session.create({
      payment_method_types: ["card"],
      success_url: checkout_success_url,
      cancel_url: checkout_cancel_url,
      line_items: cart.collect { |item| item.to_builder.attributes! },
    })
    # Redirect to stripe payment screen
    respond_to do |format|
      format.js #render app/views/checkout/create.js.erb
    end
  end

  def success
    # Transaction success
  end

  def cancel
    # Something went wrong
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def permalink
    @about = Page.find_by(permalink: params[:permalink])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pet_groups_helper.rb
module PetGroupsHelper
end

app/views/layouts/_cart.html.erb
<% if flash[:notice] %>
  <div class="row fixed-bottom d-flex justify-content-center">
    <div class="col-3">
      <div class="alert alert-info">
        <p><%= flash[:notice] %></p>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <div class="float-end margin-top">
      <%= link_to image_tag("cart.png", class: 'cart', alt: "cart"), root_path %>
      <ul>
        <li>
          Cart
          <% if cart.present? %>
            <sup><%= cart.size %></sup>
            <ul>
              <% cart.each do |breed| %>
                <li>
                  <%= breed.name %> <%= link_to '➖', cart_path(breed), method: :delete %>
                </li>
              <% end %>
            </ul>
            <%# <%= cart.collect { |item| item.to_builder.attributes! } %>
            <%= button_to 'Check Out', cart_summary_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #252531;">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Happy House Pet Adoption</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <span class="nav-link"><%= link_to 'Home', root_path %></span>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="petList" role="button" data-bs-toggle="dropdown" aria-expanded="false" >Adoptable Pet</a>
          <ul class="dropdown-menu" aria-labelledby="petList">
            <% @pet_groups_nav.each do |pg| %>
              <li><%= link_to pg.name, pg, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <span class="nav-link"><%= link_to 'Breeds', breeds_path %></span>
        </li>
        <li class="nav-item">
          <span class="nav-link"><%= link_to 'About Us', permalink_path('about') %></span>
        </li>
      </ul>
      <%= form_with(url: search_breeds_path, method: :get, local: true, class: "d-flex") do %>
        <%= text_field_tag(:keywords, nil, class: "input form-control me-2", placeholder: 'Search for Pet Breed', 'aria-label' => 'Search') %>
        <%= collection_select(:breed, :pet_group_id, PetGroup.all, :id, :name, prompt: true) %>
        <%= submit_tag("Search", class: "btn btn-outline-success") %>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link"><%= link_to 'Admin', admin_root_path %></span>
        </li>
        <li class="nav-item">
          <% if customer_signed_in? %>
            <span class="nav-link">Hi <%= current_customer.first_name %>, <%= link_to 'Sign Out', destroy_customer_session_path, method: :delete %></span>
          <% else %>
            <span class="nav-link"><%= link_to 'Sign In', new_customer_session_path %></span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy House Pet Adoption</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= render "layouts/cart" %>
            <%= yield %>
          </div>
        </div>
      </div>
    </section>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/permalink.html.erb
<h2><%= @about.title %></h2>

<% @new_line = @about.content.split("/").map(&:strip)
  @new_line.each do |item| %>
      <p><%= item %></p>
<% end %>

<% if @about.image.present? %>
  <div class="card-image">
      <figure class="image">
        <%= image_tag @about.image %>
      </figure>
    </div>
  <% else %>
    <%= image_tag("final_project.png", :alt => "ERD demonstration") %>
  <% end %>